### ISSUE TITLE
strlen does not measure the byte-length of strings

### ISSUE THREAD

**Issue by danog** [jphp-group/jphp#382]
`strlen` does not measure the actual byte length of strings, instead returning the UTF-8 length.

This can cause all sorts of unwanted behaviour, and many libraries will explicitly throw an exception if encountering such an environment (the same behaviour can be replicated in PHP with the `mbstring.func_overload` ini setting, that is typically disabled due to the unwanted side effects).

```
[daniil@daniil-arch jav]$ cat src/j.php 
<?php

var_dump(strlen('…'));

[daniil@daniil-arch jav]$ php src/j.php 
int(3)

[daniil@daniil-arch jav]$ jppm start
-> linux
-> app:run 
-> install 
int(1)
```

**Comment by dim-s** [comment]
This behavior will not be supported because in jphp, strings are a set of characters, not bytes.

**Comment by danog** [comment]
This can potentially break a lot of applications that work with raw binary data, please consider at least adding a flag to allow different behaviour.

**Comment by dim-s** [comment]
I think that it is almost impossible to achieve the level of backward compatibility with zend php, because you need to implement all the standard extensions from the original PHP, and this is more complicated than it seems at first glance.

Here the problem is not only with this function, you need to consider that a string is an array of bytes, not characters, and making support for such a flag is problematic. But in any case, it’s possible to implement such a feature.
